config/routes.rb
Rails.application.routes.draw do
  resources :grupos
  resources :estatisticas
  resources :eventos
  resources :tipo_eventos
  resources :pessoas
  resources :apresentacaos
  root 'welcome#index'
  resources :agendas
  resources :membros
  resources :visitantes
  devise_for :usuarios
end

app/models/agenda.rb
class Agenda < ApplicationRecord
	has_one_attached :imagem
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/apresentacao.rb
class Apresentacao < ApplicationRecord
    SEXO = {1 => "Masculino", 2 => "Feminino" }

    def sexo_crianca
        SEXO[self.sexo]
    end
end

app/models/estatistica.rb
class Estatistica < ApplicationRecord
end

app/models/evento.rb
class Evento < ApplicationRecord
  belongs_to :tipo_evento
  belongs_to :pessoa
end

app/models/grupo.rb
class Grupo < ApplicationRecord
end

app/models/membro.rb
class Membro < ApplicationRecord
    def nome_completo
        nome + ' ' + sobrenome
    end
end

app/models/pessoa.rb
class Pessoa < ApplicationRecord
end

app/models/tipo_evento.rb
class TipoEvento < ApplicationRecord
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/visitante.rb
class Visitante < ApplicationRecord

    belongs_to :grupo

    before_validation :sanitize_telefone

    validate :validate_unique_telefone
    validates :nome, :telefone, presence: true   
    validate :unique_nome_completo
     
    def nome_completo
        "#{self.nome} #{self.sobrenome}"
    end

    private

    def unique_nome_completo
      errors.add(:nome_completo, "já está em uso") if new_record? && Visitante.exists?(nome: nome, sobrenome: sobrenome)
    end

    def sanitize_telefone
        # Remove characters like parentheses and hyphens from telefone
        self.telefone = telefone.gsub(/[\(\)\s-]/, '') if telefone.present?
    end

    def validate_unique_telefone
        # Check uniqueness of telefone after sanitizing
        if telefone.present? && self.class.where.not(id: id).exists?(telefone: telefone)
            errors.add(:telefone, 'has already been taken')
        end
    end    
 
end

app/controllers/apresentacaos_controller.rb
class ApresentacaosController < ApplicationController
  before_action :set_apresentacao, only: %i[ show edit update destroy ]

  # GET /apresentacaos or /apresentacaos.json
  def index
    @apresentacaos = Apresentacao.all
  end

  # GET /apresentacaos/1 or /apresentacaos/1.json
  def show
  end

  # GET /apresentacaos/new
  def new
    @apresentacao = Apresentacao.new
  end

  # GET /apresentacaos/1/edit
  def edit
  end

  # POST /apresentacaos or /apresentacaos.json
  def create
    @apresentacao = Apresentacao.new(apresentacao_params)

    respond_to do |format|
      if @apresentacao.save
        format.html { redirect_to apresentacao_url(@apresentacao), notice: "Apresentacao was successfully created." }
        format.json { render :show, status: :created, location: @apresentacao }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @apresentacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apresentacaos/1 or /apresentacaos/1.json
  def update
    respond_to do |format|
      if @apresentacao.update(apresentacao_params)
        format.html { redirect_to apresentacao_url(@apresentacao), notice: "Apresentacao was successfully updated." }
        format.json { render :show, status: :ok, location: @apresentacao }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @apresentacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apresentacaos/1 or /apresentacaos/1.json
  def destroy
    @apresentacao.destroy

    respond_to do |format|
      format.html { redirect_to apresentacaos_url, notice: "Apresentacao was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apresentacao
      @apresentacao = Apresentacao.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def apresentacao_params
      params.require(:apresentacao).permit(:nome_bebe, :nome_mae, :nome_pai, :data_nascimento, :sexo, :data_apresentacao)
    end
end

app/helpers/agendas_helper.rb
module AgendasHelper
end

app/helpers/application_helper.rb
require 'uri'

module ApplicationHelper
  include Pagy::Frontend
  def is_active?(link_path)
    if params[:controller] === link_path
        "bg-violet-600 inline-block text-white rounded-full no-underline hover px-4"
    else
        "inline-block text-gray-600 rounded-full no-underline hover px-4"
    end
  end
end

app/helpers/apresentacaos_helper.rb
module ApresentacaosHelper
end

app/helpers/estatisticas_helper.rb
module EstatisticasHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/grupos_helper.rb
module GruposHelper
end

app/helpers/membros_helper.rb
module MembrosHelper
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/helpers/tipo_eventos_helper.rb
module TipoEventosHelper
end

app/helpers/visitantes_helper.rb
module VisitantesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/apresentacaos/_apresentacao.html.erb
<div id="<%= dom_id apresentacao %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Nome do bebê:</strong>
    <%= apresentacao.nome_bebe %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Nome da mae:</strong>
    <%= apresentacao.nome_mae %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Nome do pai:</strong>
    <%= apresentacao.nome_pai %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Data de nascimento:</strong>
    <%= apresentacao.data_nascimento %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Sexo:</strong>
    <%= apresentacao.sexo_crianca %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Data da apresentação:</strong>
    <%= apresentacao.data_apresentacao.strftime('%d/%m/%Y') %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Exibir", apresentacao, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Editar', edit_apresentacao_path(apresentacao), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/apresentacaos/_form.html.erb
<%= form_with(model: apresentacao, class: "contents") do |form| %>
  <% if apresentacao.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(apresentacao.errors.count, "error") %> prohibited this apresentacao from being saved:</h2>

      <ul>
        <% apresentacao.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label 'Nome do Bebê' %>
    <%= form.text_field :nome_bebe, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label 'Nome da Mãe' %>
    <%= form.text_field :nome_mae, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label 'Nome do Pai' %>
    <%= form.text_field :nome_pai, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label 'Data de nascimento' %>
    <%= form.text_field :data_nascimento, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label 'Sexo' %>
    <%= form.select :sexo, [['Masculino', 1], ['Feminino', 2]], class: "form-select appearance-none block w-full px-3 py-2 text-base font-normal text-gray-700 bg-white bg-clip-padding bg-no-repeat border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" %>
  </div>

  <div class="my-5">
    <%= form.label 'Data da apresentação' %>
    <%= form.date_field :data_apresentacao, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/apresentacaos/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editando apresentação</h1>

  <%= render "form", apresentacao: @apresentacao %>

  <%= link_to "Exibir Apresentação", @apresentacao, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Voltar para apresentações", apresentacaos_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/apresentacaos/index.html.erb
<div class="w-full">

  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Apresentacão de Bebês</h1>
    <%= link_to 'Nova Apresentação', new_apresentacao_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="apresentacaos" class="min-w-full px-5">
    <%= render @apresentacaos %>
  </div>
</div>

app/views/apresentacaos/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Nova apresentação</h1>

  <%= render "form", apresentacao: @apresentacao %>

  <%= link_to 'Voltar para Apresentações', apresentacaos_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/apresentacaos/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @apresentacao %>

    <%= link_to 'Editar', edit_apresentacao_path(@apresentacao), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Excluir', apresentacao_path(@apresentacao), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Voltar', apresentacaos_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>