config/routes.rb
Rails.application.routes.draw do
  resources :grupos
  resources :estatisticas
  resources :eventos
  resources :tipo_eventos
  resources :pessoas
  resources :apresentacaos
  root 'welcome#index'
  resources :agendas
  resources :membros
  resources :visitantes
  devise_for :usuarios
end

app/models/agenda.rb
class Agenda < ApplicationRecord
	has_one_attached :imagem
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/apresentacao.rb
class Apresentacao < ApplicationRecord
    SEXO = {1 => "Masculino", 2 => "Feminino" }

    def sexo_crianca
        SEXO[self.sexo]
    end
end

app/models/estatistica.rb
class Estatistica < ApplicationRecord
end

app/models/evento.rb
class Evento < ApplicationRecord
  belongs_to :tipo_evento
  belongs_to :pessoa
end

app/models/grupo.rb
class Grupo < ApplicationRecord
end

app/models/membro.rb
class Membro < ApplicationRecord
    def nome_completo
        nome + ' ' + sobrenome
    end
end

app/models/pessoa.rb
class Pessoa < ApplicationRecord
end

app/models/tipo_evento.rb
class TipoEvento < ApplicationRecord
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/visitante.rb
class Visitante < ApplicationRecord

    belongs_to :grupo

    before_validation :sanitize_telefone

    validate :validate_unique_telefone
    validates :nome, :telefone, presence: true   
    validate :unique_nome_completo
     
    def nome_completo
        "#{self.nome} #{self.sobrenome}"
    end

    private

    def unique_nome_completo
      errors.add(:nome_completo, "já está em uso") if new_record? && Visitante.exists?(nome: nome, sobrenome: sobrenome)
    end

    def sanitize_telefone
        # Remove characters like parentheses and hyphens from telefone
        self.telefone = telefone.gsub(/[\(\)\s-]/, '') if telefone.present?
    end

    def validate_unique_telefone
        # Check uniqueness of telefone after sanitizing
        if telefone.present? && self.class.where.not(id: id).exists?(telefone: telefone)
            errors.add(:telefone, 'has already been taken')
        end
    end    
 
end

app/controllers/pessoas_controller.rb
class PessoasController < ApplicationController
  before_action :set_pessoa, only: %i[ show edit update destroy ]

  # GET /pessoas or /pessoas.json
  def index
    @pessoas = Pessoa.all
  end

  # GET /pessoas/1 or /pessoas/1.json
  def show
  end

  # GET /pessoas/new
  def new
    @pessoa = Pessoa.new
  end

  # GET /pessoas/1/edit
  def edit
  end

  # POST /pessoas or /pessoas.json
  def create
    @pessoa = Pessoa.new(pessoa_params)

    respond_to do |format|
      if @pessoa.save
        format.html { redirect_to pessoa_url(@pessoa), notice: "Pessoa was successfully created." }
        format.json { render :show, status: :created, location: @pessoa }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pessoas/1 or /pessoas/1.json
  def update
    respond_to do |format|
      if @pessoa.update(pessoa_params)
        format.html { redirect_to pessoa_url(@pessoa), notice: "Pessoa was successfully updated." }
        format.json { render :show, status: :ok, location: @pessoa }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pessoas/1 or /pessoas/1.json
  def destroy
    @pessoa.destroy

    respond_to do |format|
      format.html { redirect_to pessoas_url, notice: "Pessoa was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pessoa
      @pessoa = Pessoa.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pessoa_params
      params.require(:pessoa).permit(:nome, :sobrenome, :nome_pai, :nome_mae, :telefone, :data_nascimento, :endereco, :bairro, :cidade, :estado, :cep, :email)
    end
end

app/helpers/agendas_helper.rb
module AgendasHelper
end

app/helpers/application_helper.rb
require 'uri'

module ApplicationHelper
  include Pagy::Frontend
  def is_active?(link_path)
    if params[:controller] === link_path
        "bg-violet-600 inline-block text-white rounded-full no-underline hover px-4"
    else
        "inline-block text-gray-600 rounded-full no-underline hover px-4"
    end
  end
end

app/helpers/apresentacaos_helper.rb
module ApresentacaosHelper
end

app/helpers/estatisticas_helper.rb
module EstatisticasHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/grupos_helper.rb
module GruposHelper
end

app/helpers/membros_helper.rb
module MembrosHelper
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/helpers/tipo_eventos_helper.rb
module TipoEventosHelper
end

app/helpers/visitantes_helper.rb
module VisitantesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/pessoas/_form.html.erb
<%= form_with(model: pessoa, class: "contents") do |form| %>
  <% if pessoa.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(pessoa.errors.count, "error") %> prohibited this pessoa from being saved:</h2>

      <ul>
        <% pessoa.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :nome %>
    <%= form.text_field :nome, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :sobrenome %>
    <%= form.text_field :sobrenome, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :nome_pai %>
    <%= form.text_field :nome_pai, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :nome_mae %>
    <%= form.text_field :nome_mae, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :telefone %>
    <%= form.text_field :telefone, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :data_nascimento %>
    <%= form.date_field :data_nascimento, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :email %>
    <%= form.text_field :email, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/pessoas/_form_modal.html.erb
<%= turbo_frame_tag :remote_modal, target: :_top do %>

    <!-- Main modal -->
    <div id="defaultModal" data-controller="modal" tabindex="-1" aria-hidden="true" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 w-full md:inset-0 h-modal md:h-full">
        <div class="relative p-4 w-full max-w-2xl h-full md:h-auto">
            <!-- Modal content -->
            <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
                <!-- Modal header -->
                <div class="flex justify-between items-start p-4 rounded-t border-b dark:border-gray-600">
                    <h3 class="text-xl font-semibold text-gray-900 dark:text-white">
                        Terms of Service
                    </h3>
                    <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-toggle="defaultModal">
                        X
                    </button>
                </div>
                <!-- Modal body -->
                <div class="p-6 space-y-6">
                    <%= render "pessoas/form", pessoa: pessoa %>
                </div>
                <!-- Modal footer -->
            </div>
        </div>
    </div>

<% end %>

app/views/pessoas/_pessoa.html.erb
<div id="<%= dom_id pessoa %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Nome:</strong>
    <%= pessoa.nome %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Sobrenome:</strong>
    <%= pessoa.sobrenome %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Nome pai:</strong>
    <%= pessoa.nome_pai %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Nome mae:</strong>
    <%= pessoa.nome_mae %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Telefone:</strong>
    <%= pessoa.telefone %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Data nascimento:</strong>
    <%= pessoa.data_nascimento %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Endereco:</strong>
    <%= pessoa.endereco %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Bairro:</strong>
    <%= pessoa.bairro %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Cidade:</strong>
    <%= pessoa.cidade %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Estado:</strong>
    <%= pessoa.estado %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Cep:</strong>
    <%= pessoa.cep %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Email:</strong>
    <%= pessoa.email %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this pessoa", pessoa, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this pessoa', edit_pessoa_path(pessoa), data: { controller: "turbo" }, class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/pessoas/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing pessoa</h1>

  <%= render "form", pessoa: @pessoa %>

  <%= link_to "Show this pessoa", @pessoa, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to pessoas", pessoas_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/pessoas/edit.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
    <%= render partial: "pessoas/form_modal", locals: { pessoa: @pessoa } %>
<% end %>

app/views/pessoas/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Pessoas</h1>
    <%= link_to 'New pessoa', new_pessoa_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="pessoas" class="min-w-full">
    <%= render @pessoas %>
  </div>
</div>

app/views/pessoas/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New pessoa</h1>

  <%= render "form", pessoa: @pessoa %>

  <%= link_to 'Back to pessoas', pessoas_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/pessoas/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @pessoa %>

    <%= link_to 'Edit this pessoa', edit_pessoa_path(@pessoa), data: { controller: "turbo" }, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this pessoa', pessoa_path(@pessoa), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to pessoas', pessoas_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>