config/routes.rb
Rails.application.routes.draw do
  resources :grupos
  resources :estatisticas
  resources :eventos
  resources :tipo_eventos
  resources :pessoas
  resources :apresentacaos
  root 'welcome#index'
  resources :agendas
  resources :membros
  resources :visitantes
  devise_for :usuarios
end

app/models/agenda.rb
class Agenda < ApplicationRecord
	has_one_attached :imagem
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/apresentacao.rb
class Apresentacao < ApplicationRecord
    SEXO = {1 => "Masculino", 2 => "Feminino" }

    def sexo_crianca
        SEXO[self.sexo]
    end
end

app/models/estatistica.rb
class Estatistica < ApplicationRecord
end

app/models/evento.rb
class Evento < ApplicationRecord
  belongs_to :tipo_evento
  belongs_to :pessoa
end

app/models/grupo.rb
class Grupo < ApplicationRecord
end

app/models/membro.rb
class Membro < ApplicationRecord
    def nome_completo
        nome + ' ' + sobrenome
    end
end

app/models/pessoa.rb
class Pessoa < ApplicationRecord
end

app/models/tipo_evento.rb
class TipoEvento < ApplicationRecord
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/visitante.rb
class Visitante < ApplicationRecord

    belongs_to :grupo

    before_validation :sanitize_telefone

    validate :validate_unique_telefone
    validates :nome, :telefone, presence: true   
    validate :unique_nome_completo
     
    def nome_completo
        "#{self.nome} #{self.sobrenome}"
    end

    private

    def unique_nome_completo
      errors.add(:nome_completo, "já está em uso") if new_record? && Visitante.exists?(nome: nome, sobrenome: sobrenome)
    end

    def sanitize_telefone
        # Remove characters like parentheses and hyphens from telefone
        self.telefone = telefone.gsub(/[\(\)\s-]/, '') if telefone.present?
    end

    def validate_unique_telefone
        # Check uniqueness of telefone after sanitizing
        if telefone.present? && self.class.where.not(id: id).exists?(telefone: telefone)
            errors.add(:telefone, 'has already been taken')
        end
    end    
 
end

app/helpers/agendas_helper.rb
module AgendasHelper
end

app/helpers/application_helper.rb
require 'uri'

module ApplicationHelper
  include Pagy::Frontend
  def is_active?(link_path)
    if params[:controller] === link_path
        "bg-violet-600 inline-block text-white rounded-full no-underline hover px-4"
    else
        "inline-block text-gray-600 rounded-full no-underline hover px-4"
    end
  end
end

app/helpers/estatisticas_helper.rb
module EstatisticasHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/grupos_helper.rb
module GruposHelper
end

app/helpers/membros_helper.rb
module MembrosHelper
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/helpers/visitantes_helper.rb
module VisitantesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/menus/_reports.html.erb
<div class="relative" data-controller="dropdown">
    <button data-action="click->dropdown#toggle" class="text-white font-semibold text-[15px]">
        Relatórios
        <svg
            xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" class="ml-1 inline-block"
            viewBox="0 0 24 24">
            <path
            d="M12 16a1 1 0 0 1-.71-.29l-6-6a1 1 0 0 1 1.42-1.42l5.29 5.3 5.29-5.29a1 1 0 0 1 1.41 1.41l-6 6a1 1 0 0 1-.7.29z"
            data-name="16" data-original="#FFFFFF" />
        </svg>      
    </button>
    <div data-dropdown-target="menu" class="absolute hidden bg-white text-black mt-2 py-2 w-48 rounded shadow-lg min-w-[250px]">
        <a href="#" class="hover:text-[#007bff] hover:fill-[#007bff] text-gray-600 font-semibold text-[15px] block px-4 py-2">Relatório 1</a>
        <div class="relative" data-controller="dropdown">
            <button data-action="click->dropdown#toggle" class="hover:text-[#007bff] hover:fill-[#007bff] text-gray-600 font-semibold text-[15px] block px-4 py-2 w-full text-left flex justify-between">
                Relatório 2
                <svg width="16" height="16" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg" fill="#000000" style="margin-top: 0.38em;">
                    <path d="M6.29 16.29a1 1 0 010-1.41L11.58 10 6.29 4.71a1 1 0 111.41-1.41l6 6a1 1 0 010 1.41l-6 6a1 1 0 01-1.41 0z"/>
                </svg>
            </button>
            <div data-dropdown-target="menu" class="absolute hidden bg-white text-black mt-2 py-2 w-48 rounded shadow-lg left-full top-0 min-w-[250px]">
                <a href="#" class="hover:text-[#007bff] hover:fill-[#007bff] text-gray-600 font-semibold text-[15px] block px-4 py-2">Relatório 2 por nome</a>
                <a href="#" class="hover:text-[#007bff] hover:fill-[#007bff] text-gray-600 font-semibold text-[15px] block px-4 py-2">Relatório 2 por codigo</a>
            </div>
        </div>  
    </div>
</div> 

app/views/shared/_footer.html.erb
<% if usuario_signed_in? %>
<footer class="text-center bg-gray-900 text-white static bottom-0">
  <div class="container-full px-6 pt-6">
    <div class="flex justify-center mb-6">
      <a href="#!" type="button" class="rounded-full border-2 border-white text-white leading-normal uppercase hover:bg-black hover:bg-opacity-5 focus:outline-none focus:ring-0 transition duration-150 ease-in-out w-9 h-9 m-1">
        <svg aria-hidden="true"
        focusable="false"
        data-prefix="fab"
        data-icon="facebook-f"
        class="w-2 h-full mx-auto"
        role="img"
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 320 512"
      >
        <path
          fill="currentColor"
          d="M279.14 288l14.22-92.66h-88.91v-60.13c0-25.35 12.42-50.06 52.24-50.06h40.42V6.26S260.43 0 225.36 0c-73.22 0-121.08 44.38-121.08 124.72v70.62H22.89V288h81.39v224h100.17V288z"
        ></path>
        </svg>
      </a>

      <a href="#!" type="button" class="rounded-full border-2 border-white text-white leading-normal uppercase hover:bg-black hover:bg-opacity-5 focus:outline-none focus:ring-0 transition duration-150 ease-in-out w-9 h-9 m-1">
        <svg aria-hidden="true"
        focusable="false"
        data-prefix="fab"
          data-icon="twitter"
          class="w-3 h-full mx-auto"
          role="img"
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 512 512"
        >
          <path
            fill="currentColor"
            d="M459.37 151.716c.325 4.548.325 9.097.325 13.645 0 138.72-105.583 298.558-298.558 298.558-59.452 0-114.68-17.219-161.137-47.106 8.447.974 16.568 1.299 25.34 1.299 49.055 0 94.213-16.568 130.274-44.832-46.132-.975-84.792-31.188-98.112-72.772 6.498.974 12.995 1.624 19.818 1.624 9.421 0 18.843-1.3 27.614-3.573-48.081-9.747-84.143-51.98-84.143-102.985v-1.299c13.969 7.797 30.214 12.67 47.431 13.319-28.264-18.843-46.781-51.005-46.781-87.391 0-19.492 5.197-37.36 14.294-52.954 51.655 63.675 129.3 105.258 216.365 109.807-1.624-7.797-2.599-15.918-2.599-24.04 0-57.828 46.782-104.934 104.934-104.934 30.213 0 57.502 12.67 76.67 33.137 23.715-4.548 46.456-13.32 66.599-25.34-7.798 24.366-24.366 44.833-46.132 57.827 21.117-2.273 41.584-8.122 60.426-16.243-14.292 20.791-32.161 39.308-52.628 54.253z"
          ></path>
        </svg>
      </a>

      <a href="#!" type="button" class="rounded-full border-2 border-white text-white leading-normal uppercase hover:bg-black hover:bg-opacity-5 focus:outline-none focus:ring-0 transition duration-150 ease-in-out w-9 h-9 m-1">
        <svg aria-hidden="true"
        focusable="false"
        data-prefix="fab"
          data-icon="google"
          class="w-3 h-full mx-auto"
          role="img"
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 488 512"
        >
          <path
            fill="currentColor"
            d="M488 261.8C488 403.3 391.1 504 248 504 110.8 504 0 393.2 0 256S110.8 8 248 8c66.8 0 123 24.5 166.3 64.9l-67.5 64.9C258.5 52.6 94.3 116.6 94.3 256c0 86.5 69.1 156.6 153.7 156.6 98.2 0 135-70.4 140.8-106.9H248v-85.3h236.1c2.3 12.7 3.9 24.9 3.9 41.4z"
          ></path>
        </svg>
      </a>

      <a href="#!" type="button" class="rounded-full border-2 border-white text-white leading-normal uppercase hover:bg-black hover:bg-opacity-5 focus:outline-none focus:ring-0 transition duration-150 ease-in-out w-9 h-9 m-1">
        <svg aria-hidden="true"
        focusable="false"
        data-prefix="fab"
        data-icon="instagram"
          class="w-3 h-full mx-auto"
          role="img"
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 448 512"
        >
          <path
            fill="currentColor"
            d="M224.1 141c-63.6 0-114.9 51.3-114.9 114.9s51.3 114.9 114.9 114.9S339 319.5 339 255.9 287.7 141 224.1 141zm0 189.6c-41.1 0-74.7-33.5-74.7-74.7s33.5-74.7 74.7-74.7 74.7 33.5 74.7 74.7-33.6 74.7-74.7 74.7zm146.4-194.3c0 14.9-12 26.8-26.8 26.8-14.9 0-26.8-12-26.8-26.8s12-26.8 26.8-26.8 26.8 12 26.8 26.8zm76.1 27.2c-1.7-35.9-9.9-67.7-36.2-93.9-26.2-26.2-58-34.4-93.9-36.2-37-2.1-147.9-2.1-184.9 0-35.8 1.7-67.6 9.9-93.9 36.1s-34.4 58-36.2 93.9c-2.1 37-2.1 147.9 0 184.9 1.7 35.9 9.9 67.7 36.2 93.9s58 34.4 93.9 36.2c37 2.1 147.9 2.1 184.9 0 35.9-1.7 67.7-9.9 93.9-36.2 26.2-26.2 34.4-58 36.2-93.9 2.1-37 2.1-147.8 0-184.8zM398.8 388c-7.8 19.6-22.9 34.7-42.6 42.6-29.5 11.7-99.5 9-132.1 9s-102.7 2.6-132.1-9c-19.6-7.8-34.7-22.9-42.6-42.6-11.7-29.5-9-99.5-9-132.1s-2.6-102.7 9-132.1c7.8-19.6 22.9-34.7 42.6-42.6 29.5-11.7 99.5-9 132.1-9s102.7-2.6 132.1 9c19.6 7.8 34.7 22.9 42.6 42.6 11.7 29.5 9 99.5 9 132.1s2.7 102.7-9 132.1z"
          ></path>
        </svg>
      </a>

      <a href="#!" type="button" class="rounded-full border-2 border-white text-white leading-normal uppercase hover:bg-black hover:bg-opacity-5 focus:outline-none focus:ring-0 transition duration-150 ease-in-out w-9 h-9 m-1">
        <svg aria-hidden="true"
        focusable="false"
        data-prefix="fab"
        data-icon="linkedin-in"
          class="w-3 h-full mx-auto"
          role="img"
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 448 512"
        >
          <path
            fill="currentColor"
            d="M100.28 448H7.4V148.9h92.88zM53.79 108.1C24.09 108.1 0 83.5 0 53.8a53.79 53.79 0 0 1 107.58 0c0 29.7-24.1 54.3-53.79 54.3zM447.9 448h-92.68V302.4c0-34.7-.7-79.2-48.29-79.2-48.29 0-55.69 37.7-55.69 76.7V448h-92.78V148.9h89.08v40.8h1.3c12.4-23.5 42.69-48.3 87.88-48.3 94 0 111.28 61.9 111.28 142.3V448z"
          ></path>
        </svg>
      </a>

      <a href="#!" type="button" class="rounded-full border-2 border-white text-white leading-normal uppercase hover:bg-black hover:bg-opacity-5 focus:outline-none focus:ring-0 transition duration-150 ease-in-out w-9 h-9 m-1">
        <svg aria-hidden="true"
        focusable="false"
        data-prefix="fab"
        data-icon="github"
          class="w-3 h-full mx-auto"
          role="img"
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 496 512"
        >
          <path
            fill="currentColor"
            d="M165.9 397.4c0 2-2.3 3.6-5.2 3.6-3.3.3-5.6-1.3-5.6-3.6 0-2 2.3-3.6 5.2-3.6 3-.3 5.6 1.3 5.6 3.6zm-31.1-4.5c-.7 2 1.3 4.3 4.3 4.9 2.6 1 5.6 0 6.2-2s-1.3-4.3-4.3-5.2c-2.6-.7-5.5.3-6.2 2.3zm44.2-1.7c-2.9.7-4.9 2.6-4.6 4.9.3 2 2.9 3.3 5.9 2.6 2.9-.7 4.9-2.6 4.6-4.6-.3-1.9-3-3.2-5.9-2.9zM244.8 8C106.1 8 0 113.3 0 252c0 110.9 69.8 205.8 169.5 239.2 12.8 2.3 17.3-5.6 17.3-12.1 0-6.2-.3-40.4-.3-61.4 0 0-70 15-84.7-29.8 0 0-11.4-29.1-27.8-36.6 0 0-22.9-15.7 1.6-15.4 0 0 24.9 2 38.6 25.8 21.9 38.6 58.6 27.5 72.9 20.9 2.3-16 8.8-27.1 16-33.7-55.9-6.2-112.3-14.3-112.3-110.5 0-27.5 7.6-41.3 23.6-58.9-2.6-6.5-11.1-33.3 2.6-67.9 20.9-6.5 69 27 69 27 20-5.6 41.5-8.5 62.8-8.5s42.8 2.9 62.8 8.5c0 0 48.1-33.6 69-27 13.7 34.7 5.2 61.4 2.6 67.9 16 17.7 25.8 31.5 25.8 58.9 0 96.5-58.9 104.2-114.8 110.5 9.2 7.9 17 22.9 17 46.4 0 33.7-.3 75.4-.3 83.6 0 6.5 4.6 14.4 17.3 12.1C428.2 457.8 496 362.9 496 252 496 113.3 383.5 8 244.8 8zM97.2 352.9c-1.3 1-1 3.3.7 5.2 1.6 1.6 3.9 2.3 5.2 1 1.3-1 1-3.3-.7-5.2-1.6-1.6-3.9-2.3-5.2-1zm-10.8-8.1c-.7 1.3.3 2.9 2.3 3.9 1.6 1 3.6.7 4.3-.7.7-1.3-.3-2.9-2.3-3.9-2-.6-3.6-.3-4.3.7zm32.4 35.6c-1.6 1.3-1 4.3 1.3 6.2 2.3 2.3 5.2 2.6 6.5 1 1.3-1.3.7-4.3-1.3-6.2-2.2-2.3-5.2-2.6-6.5-1zm-11.4-14.7c-1.6 1-1.6 3.6 0 5.9 1.6 2.3 4.3 3.3 5.6 2.3 1.6-1.3 1.6-3.9 0-6.2-1.4-2.3-4-3.3-5.6-2z"
          ></path>
        </svg>
      </a>
    </div>
  </div>

  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2022 Copyright:
    <a class="text-whitehite" href="https://kallario.com.br/">Kalla Rio Tecnologia</a>
  </div>
</footer>
<% end %>

app/views/shared/_navbar.html.erb
<div class="flex justify-between w-full bg-gray-800 text-white items-center p-4">
  <div class="w-32">
    <%= image_tag 'logo.png' %>
  </div>
  <%= button_to destroy_usuario_session_path, method: :delete, class: "text-white font-semibold text-[15px] mt-[0.05em]" do %>
      Sair do Sistema
  <% end %>   
</div>
<header class='shadow-md bg-orange-600 font-[sans-serif] tracking-wide relative z-50'>
  <div class='flex flex-wrap justify-center px-10 py-3 relative'>
    <nav>
      <div class="container mx-auto flex items-center justify-between">
        <div class="lg:flex lg:gap-x-10 max-lg:space-y-3 max-lg:fixed max-lg:bg-white max-lg:w-2/3 max-lg:min-w-[300px] max-lg:top-0 max-lg:left-0 max-lg:p-4 max-lg:h-full max-lg:shadow-md max-lg:overflow-auto z-50">
          <%= link_to root_path, class: "text-white font-semibold text-[15px] mt-[0.05em]" do %>
              Principal
          <% end %>
          <%= link_to visitantes_path, class: "text-white font-semibold text-[15px] mt-[0.05em]" do %>
              Pessoas
          <% end %>
          <%= link_to estatisticas_path, class: "text-white font-semibold text-[15px] mt-[0.05em]" do %>
            Celebrações
          <% end %>                     
          <%= render 'layouts/menus/reports'%>           
        </div>
      </div>
    </nav>
  </div>
</header>

app/views/shared/_sidebar.html.erb
   <div class="overflow-y-auto py-4 px-3 bg-gray-50 rounded dark:bg-gray-800">

   </div>