config/routes.rb
Rails.application.routes.draw do
  resources :grupos
  resources :estatisticas
  resources :eventos
  resources :tipo_eventos
  resources :pessoas
  resources :apresentacaos
  root 'welcome#index'
  resources :agendas
  resources :membros
  resources :visitantes
  devise_for :usuarios
end

app/models/agenda.rb
class Agenda < ApplicationRecord
	has_one_attached :imagem
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/apresentacao.rb
class Apresentacao < ApplicationRecord
    SEXO = {1 => "Masculino", 2 => "Feminino" }

    def sexo_crianca
        SEXO[self.sexo]
    end
end

app/models/estatistica.rb
class Estatistica < ApplicationRecord
end

app/models/evento.rb
class Evento < ApplicationRecord
  belongs_to :tipo_evento
  belongs_to :pessoa
end

app/models/grupo.rb
class Grupo < ApplicationRecord
end

app/models/membro.rb
class Membro < ApplicationRecord
    def nome_completo
        nome + ' ' + sobrenome
    end
end

app/models/pessoa.rb
class Pessoa < ApplicationRecord
end

app/models/tipo_evento.rb
class TipoEvento < ApplicationRecord
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/visitante.rb
class Visitante < ApplicationRecord

    belongs_to :grupo

    before_validation :sanitize_telefone

    validate :validate_unique_telefone
    validates :nome, :telefone, presence: true   
    validate :unique_nome_completo
     
    def nome_completo
        "#{self.nome} #{self.sobrenome}"
    end

    private

    def unique_nome_completo
      errors.add(:nome_completo, "já está em uso") if new_record? && Visitante.exists?(nome: nome, sobrenome: sobrenome)
    end

    def sanitize_telefone
        # Remove characters like parentheses and hyphens from telefone
        self.telefone = telefone.gsub(/[\(\)\s-]/, '') if telefone.present?
    end

    def validate_unique_telefone
        # Check uniqueness of telefone after sanitizing
        if telefone.present? && self.class.where.not(id: id).exists?(telefone: telefone)
            errors.add(:telefone, 'has already been taken')
        end
    end    
 
end

app/controllers/tipo_eventos_controller.rb
class TipoEventosController < ApplicationController
  before_action :set_tipo_evento, only: %i[ show edit update destroy ]

  # GET /tipo_eventos or /tipo_eventos.json
  def index
    @tipo_eventos = TipoEvento.all
  end

  # GET /tipo_eventos/1 or /tipo_eventos/1.json
  def show
  end

  # GET /tipo_eventos/new
  def new
    @tipo_evento = TipoEvento.new
  end

  # GET /tipo_eventos/1/edit
  def edit
  end

  # POST /tipo_eventos or /tipo_eventos.json
  def create
    @tipo_evento = TipoEvento.new(tipo_evento_params)

    respond_to do |format|
      if @tipo_evento.save
        format.html { redirect_to tipo_evento_url(@tipo_evento), notice: "Tipo evento was successfully created." }
        format.json { render :show, status: :created, location: @tipo_evento }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tipo_evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipo_eventos/1 or /tipo_eventos/1.json
  def update
    respond_to do |format|
      if @tipo_evento.update(tipo_evento_params)
        format.html { redirect_to tipo_evento_url(@tipo_evento), notice: "Tipo evento was successfully updated." }
        format.json { render :show, status: :ok, location: @tipo_evento }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tipo_evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_eventos/1 or /tipo_eventos/1.json
  def destroy
    @tipo_evento.destroy

    respond_to do |format|
      format.html { redirect_to tipo_eventos_url, notice: "Tipo evento was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo_evento
      @tipo_evento = TipoEvento.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tipo_evento_params
      params.require(:tipo_evento).permit(:descricao)
    end
end

app/helpers/agendas_helper.rb
module AgendasHelper
end

app/helpers/application_helper.rb
require 'uri'

module ApplicationHelper
  include Pagy::Frontend
  def is_active?(link_path)
    if params[:controller] === link_path
        "bg-violet-600 inline-block text-white rounded-full no-underline hover px-4"
    else
        "inline-block text-gray-600 rounded-full no-underline hover px-4"
    end
  end
end

app/helpers/apresentacaos_helper.rb
module ApresentacaosHelper
end

app/helpers/estatisticas_helper.rb
module EstatisticasHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/grupos_helper.rb
module GruposHelper
end

app/helpers/membros_helper.rb
module MembrosHelper
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/helpers/tipo_eventos_helper.rb
module TipoEventosHelper
end

app/helpers/visitantes_helper.rb
module VisitantesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/tipo_eventos/_form.html.erb
<%= form_with(model: tipo_evento, class: "contents") do |form| %>
  <% if tipo_evento.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(tipo_evento.errors.count, "error") %> prohibited this tipo_evento from being saved:</h2>

      <ul>
        <% tipo_evento.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :descricao %>
    <%= form.text_field :descricao, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/tipo_eventos/_tipo_evento.html.erb
<div id="<%= dom_id tipo_evento %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Descricao:</strong>
    <%= tipo_evento.descricao %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this tipo evento", tipo_evento, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this tipo evento', edit_tipo_evento_path(tipo_evento), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/tipo_eventos/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing tipo evento</h1>

  <%= render "form", tipo_evento: @tipo_evento %>

  <%= link_to "Show this tipo evento", @tipo_evento, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to tipo eventos", tipo_eventos_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/tipo_eventos/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Tipo eventos</h1>
    <%= link_to 'New tipo evento', new_tipo_evento_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="tipo_eventos" class="min-w-full">
    <%= render @tipo_eventos %>
  </div>
</div>

app/views/tipo_eventos/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New tipo evento</h1>

  <%= render "form", tipo_evento: @tipo_evento %>

  <%= link_to 'Back to tipo eventos', tipo_eventos_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/tipo_eventos/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @tipo_evento %>

    <%= link_to 'Edit this tipo_evento', edit_tipo_evento_path(@tipo_evento), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this tipo_evento', tipo_evento_path(@tipo_evento), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to tipo_eventos', tipo_eventos_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>